"use client";

import useSWR from "swr";
import { SectionHeader } from "@/components/layout/SectionHeader";
import { ChartCard } from "@/components/shared/ChartCard";
import { Badge } from "@/components/ui/badge";
import type { NarrativeEventsResponse } from "@/lib/types";

const fetcher = (url: string) => fetch(url).then((r) => r.json());

export default function EventsPage() {
  const { data } = useSWR<NarrativeEventsResponse>("/api/analysis/narrative-events", fetcher);
  const events = data?.items ?? [];

  return (
    <div className="space-y-6">
      <SectionHeader
        eyebrow="Intelligence"
        title="Narrative events"
        subtitle="Persisted anomaly and lifecycle signals generated by the analysis artifact pipeline."
      />

      <ChartCard title="Event timeline" subtitle={`${events.length} persisted events`}>
        {data?.state && data.state !== "ready" && (
          <div className="mb-3 rounded-md border border-signal-yellow/25 bg-signal-yellow/10 px-3 py-2 text-xs text-signal-yellow">
            {data.provenance?.detail ?? data.state.replace("_", " ")}
          </div>
        )}
        <div className="space-y-3">
          {events.length ? events.map((event) => (
            <article key={event.event_id} className="grid gap-3 rounded-md border border-border bg-background/35 p-4 md:grid-cols-[160px_1fr_auto]">
              <div className="font-mono text-xs text-muted-foreground">
                <p>{event.peak_date}</p>
                <p>{event.start_date} - {event.end_date}</p>
              </div>
              <div className="min-w-0">
                <h3 className="text-sm font-semibold text-foreground">{event.title}</h3>
                <p className="mt-1 text-sm text-muted-foreground">{event.summary}</p>
                <div className="mt-2 flex flex-wrap gap-1">
                  {event.top_terms.slice(0, 6).map((term) => (
                    <span key={term} className="rounded border border-signal-copper/25 bg-signal-copper/8 px-2 py-0.5 font-mono text-[10px] text-signal-copper">{term}</span>
                  ))}
                </div>
              </div>
              <Badge variant={event.sentiment_delta && event.sentiment_delta < 0 ? "destructive" : "secondary"}>
                {event.lifecycle_state}
              </Badge>
            </article>
          )) : (
            <div className="grid h-40 place-items-center text-sm text-muted-foreground">
              No narrative events are available yet.
            </div>
          )}
        </div>
      </ChartCard>
    </div>
  );
}
