"""
ML Layer — Topic Modeling

Discovers and tracks themes in Reddit discussions using BERTopic.
Reuses the all-MiniLM-L6-v2 embeddings generated by preprocessing.py.
"""

import json
import logging
import math
from collections import defaultdict
from datetime import datetime, timedelta
from pathlib import Path
from typing import Dict, List, Optional, Tuple, Union

import numpy as np

from src.ml.db import (
    ensure_topics_tables,
    get_connection,
    iter_preprocessed_for_topics,
    upsert_topic_assignments,
    upsert_topic_over_time,
    upsert_topics,
)

logger = logging.getLogger(__name__)

# --- Constants ---
OUTLIER_TOPIC_ID = -1
MIN_TOPIC_COUNT_GATE = 20
MIN_COHERENCE_GATE = 0.50
EMBEDDING_DIM = 384
SENTIMENT_SCORE_MAP = {"positive": 1.0, "neutral": 0.0, "negative": -1.0}
_SENTIMENT_BATCH = 999  # SQLite max safe parameters per query


def _detect_device() -> str:
    """Return the best available PyTorch device: mps → cuda → cpu."""
    try:
        import torch

        if torch.backends.mps.is_available():
            return "mps"
        if torch.cuda.is_available():
            return "cuda"
    except ImportError:
        pass
    return "cpu"


def _week_start(ts_str: str) -> Optional[str]:
    """Return the ISO Monday (YYYY-MM-DD) for a timestamp string, or None."""
    try:
        dt = datetime.fromisoformat(str(ts_str))
        monday = dt - timedelta(days=dt.weekday())
        return monday.strftime("%Y-%m-%d")
    except (ValueError, TypeError):
        return None


class EmbeddingCache:
    """Read-only wrapper around the numpy embedding cache from preprocessing."""

    def __init__(self, cache_dir: str = "models/") -> None:
        base = Path(cache_dir)
        self._cache_path = base / "embeddings_cache.npy"
        self._index_path = base / "embeddings_index.json"
        self._embeddings: Optional[np.ndarray] = None
        self._index: Optional[Dict[str, int]] = None

    def load(self) -> Tuple[np.ndarray, Dict[str, int]]:
        if self._embeddings is not None and self._index is not None:
            return self._embeddings, self._index
        if not self._cache_path.exists():
            raise FileNotFoundError(
                f"Embedding cache not found at {self._cache_path}. "
                "Run preprocessing first."
            )
        if not self._index_path.exists():
            raise FileNotFoundError(
                f"Embedding index not found at {self._index_path}. "
                "Run preprocessing first."
            )
        embeddings = np.load(str(self._cache_path))
        with open(self._index_path) as f:
            index: Dict[str, int] = json.load(f)
        self._embeddings = embeddings
        self._index = index
        return embeddings, index

    def get_subset(self, embedding_keys: List[str]) -> np.ndarray:
        """Extract rows for the given keys using numpy fancy indexing."""
        embeddings, index = self.load()
        row_indices = []
        n_embeddings = len(embeddings)
        for key in embedding_keys:
            if key in index:
                row_indices.append(index[key])
            elif key.lstrip("-").isdigit() and 0 <= int(key) < n_embeddings:
                row_indices.append(int(key))
            else:
                logger.warning("Embedding key not in cache, skipping: %s", key)
        if not row_indices:
            return np.zeros((0, EMBEDDING_DIM), dtype=np.float32)
        return embeddings[row_indices]


class TopicModeler:
    """BERTopic wrapper with UMass coherence scoring and gate checking."""

    def __init__(
        self,
        cache_dir: str = "models/",
        n_neighbors: int = 15,
        n_components: int = 5,
        min_cluster_size: int = 30,
        nr_topics: Union[int, str] = "auto",
        min_topic_size: int = 30,
    ) -> None:
        self.cache_dir = cache_dir
        self.n_neighbors = n_neighbors
        self.n_components = n_components
        self.min_cluster_size = min_cluster_size
        self.nr_topics = nr_topics
        self.min_topic_size = min_topic_size
        self._model = None
        self._doc_topics: List[int] = []

    def _build_model(self):
        """Construct a configured BERTopic instance and store as self._model."""
        from bertopic import BERTopic
        from hdbscan import HDBSCAN
        from umap import UMAP

        umap_model = UMAP(
            n_neighbors=self.n_neighbors,
            n_components=self.n_components,
            min_dist=0.0,
            metric="cosine",
            random_state=42,
        )
        hdbscan_model = HDBSCAN(
            min_cluster_size=self.min_cluster_size,
            metric="euclidean",
            cluster_selection_method="eom",
            prediction_data=True,
        )
        self._model = BERTopic(
            umap_model=umap_model,
            hdbscan_model=hdbscan_model,
            nr_topics=self.nr_topics,
            min_topic_size=self.min_topic_size,
            calculate_probabilities=True,
            verbose=False,
        )
        return self._model

    def train(
        self, docs: List[str], embeddings: np.ndarray
    ) -> Tuple[List[int], np.ndarray]:
        """Fit BERTopic on docs + precomputed embeddings."""
        if self._model is None:
            raise RuntimeError("Call _build_model() before train().")
        topics, probs = self._model.fit_transform(docs, embeddings)
        self._doc_topics = list(topics)
        # probs may be 2D (N, n_topics) with HDBSCAN — flatten to (N,)
        arr = np.asarray(probs, dtype=np.float32)
        if arr.ndim == 2:
            arr = arr.max(axis=1)
        return self._doc_topics, arr

    def get_topic_info(self) -> List[Dict]:
        """Return per-topic metadata including the outlier topic -1."""
        if self._model is None:
            return []
        df = self._model.get_topic_info()
        outlier_count = self._doc_topics.count(OUTLIER_TOPIC_ID)
        result = []
        for _, row in df.iterrows():
            topic_id = int(row["Topic"])
            if topic_id == OUTLIER_TOPIC_ID:
                result.append(
                    {"topic_id": OUTLIER_TOPIC_ID, "keywords": [], "doc_count": outlier_count}
                )
                continue
            raw = self._model.get_topic(topic_id)
            keywords = [w for w, _ in raw] if raw else []
            result.append(
                {
                    "topic_id": topic_id,
                    "keywords": keywords,
                    "doc_count": int(row["Count"]),
                }
            )
        return result

    def compute_coherence(self, topic_id: int, docs: List[str]) -> float:
        """
        UMass coherence for a topic using its top-10 keywords.

        Score is exp(mean UMass) mapped to (0, 1]. No external corpus needed.
        """
        if self._model is None:
            return 0.0
        raw = self._model.get_topic(topic_id)
        if not raw:
            return 0.0
        keywords = [w.lower() for w, _ in raw[:10]]
        if len(keywords) < 2:
            return 0.0

        topic_docs = [
            docs[i].lower()
            for i, t in enumerate(self._doc_topics)
            if t == topic_id
        ]
        n = len(topic_docs)
        if n == 0:
            return 0.0

        scores = []
        for i in range(1, len(keywords)):
            w_i = keywords[i]
            for j in range(i):
                w_j = keywords[j]
                d_wj = sum(1 for d in topic_docs if w_j in d)
                d_wi_wj = sum(1 for d in topic_docs if w_i in d and w_j in d)
                scores.append(math.log((d_wi_wj + 1) / (d_wj + 1)))

        if not scores:
            return 0.0
        raw_score = sum(scores) / len(scores)
        # exp maps (-inf, 0] → (0, 1]
        return float(math.exp(raw_score))

    def check_gate(self, coherence_scores: List[float]) -> Tuple[bool, Dict]:
        """Pass if >= MIN_TOPIC_COUNT_GATE topics have coherence >= MIN_COHERENCE_GATE."""
        if not coherence_scores:
            return False, {
                "passed": False,
                "n_coherent_topics": 0,
                "mean_coherence": 0.0,
                "min_threshold": MIN_COHERENCE_GATE,
                "count_threshold": MIN_TOPIC_COUNT_GATE,
            }
        n_coherent = sum(1 for s in coherence_scores if s >= MIN_COHERENCE_GATE)
        mean_coh = sum(coherence_scores) / len(coherence_scores)
        passed = n_coherent >= MIN_TOPIC_COUNT_GATE
        return passed, {
            "passed": passed,
            "n_coherent_topics": n_coherent,
            "mean_coherence": round(mean_coh, 4),
            "min_threshold": MIN_COHERENCE_GATE,
            "count_threshold": MIN_TOPIC_COUNT_GATE,
        }


def run_topic_modeling(
    db_path: str,
    cache_dir: str = "models/",
    days: int = 90,
    batch_size: int = 1000,
    n_neighbors: int = 15,
    n_components: int = 5,
    min_cluster_size: int = 30,
    nr_topics: Union[int, str] = "auto",
    min_topic_size: int = 30,
    mlflow_tracking: bool = True,
    skip_gate_check: bool = False,
) -> Dict:
    """
    Full topic modeling pipeline: load embeddings, train BERTopic,
    compute coherence, and write topics/assignments/temporal data to SQLite.

    Returns summary dict: total_docs, n_topics, n_outliers,
    coherent_topic_count, mean_coherence, gate_passed, device, days.
    """
    device = _detect_device()
    _mlflow_run = None
    if mlflow_tracking:
        try:
            import mlflow

            mlflow.set_experiment("reddit-analyzer-phase2")
            _mlflow_run = mlflow.start_run(run_name="week3-topic-modeling")
            mlflow.log_params(
                {
                    "days": days,
                    "min_cluster_size": min_cluster_size,
                    "nr_topics": str(nr_topics),
                    "min_topic_size": min_topic_size,
                    "n_neighbors": n_neighbors,
                    "n_components": n_components,
                    "device": device,
                }
            )
        except Exception as exc:
            logger.warning("MLflow unavailable: %s", exc)
            _mlflow_run = None

    conn = get_connection(db_path)
    try:
        ensure_topics_tables(conn)

        # --- Step 1: Load all records from rolling window ---
        all_ids: List[str] = []
        all_docs: List[str] = []
        all_embedding_keys: List[str] = []
        all_source_timestamps: List[Optional[str]] = []

        for batch in iter_preprocessed_for_topics(conn, days=days, batch_size=batch_size):
            for row in batch:
                all_ids.append(row["id"])
                all_docs.append(row["clean_text"])
                all_embedding_keys.append(row["embedding_key"])
                all_source_timestamps.append(row["source_timestamp"])

        total_docs = len(all_docs)
        logger.info("Loaded %d documents for topic modeling.", total_docs)

        if total_docs == 0:
            logger.warning("No documents found — run preprocessing first.")
            return {
                "total_docs": 0,
                "n_topics": 0,
                "n_outliers": 0,
                "coherent_topic_count": 0,
                "mean_coherence": 0.0,
                "gate_passed": False,
                "device": device,
                "days": days,
            }

        # --- Step 2: Load embedding subset ---
        cache = EmbeddingCache(cache_dir)
        embeddings = cache.get_subset(all_embedding_keys)

        # Trim if some keys were not in cache
        if len(embeddings) < total_docs:
            logger.warning(
                "Only %d embeddings for %d docs; trimming.", len(embeddings), total_docs
            )
            _, idx = cache.load()
            valid = [k in idx for k in all_embedding_keys]
            all_ids = [x for x, v in zip(all_ids, valid) if v]
            all_docs = [x for x, v in zip(all_docs, valid) if v]
            all_source_timestamps = [x for x, v in zip(all_source_timestamps, valid) if v]
            total_docs = len(all_docs)

        # --- Step 3: Train BERTopic ---
        modeler = TopicModeler(
            cache_dir=cache_dir,
            n_neighbors=n_neighbors,
            n_components=n_components,
            min_cluster_size=min_cluster_size,
            nr_topics=nr_topics,
            min_topic_size=min_topic_size,
        )
        modeler._build_model()
        topic_assignments, probs = modeler.train(all_docs, embeddings)

        # --- Step 4: Coherence scoring ---
        topic_info = modeler.get_topic_info()
        coherence_by_id: Dict[int, float] = {}
        for info in topic_info:
            tid = info["topic_id"]
            if tid != OUTLIER_TOPIC_ID:
                coherence_by_id[tid] = modeler.compute_coherence(tid, all_docs)

        gate_passed, gate_report = modeler.check_gate(list(coherence_by_id.values()))
        if gate_passed:
            logger.info(
                "Gate PASSED: %d coherent topics, mean coherence %.3f",
                gate_report["n_coherent_topics"],
                gate_report["mean_coherence"],
            )
        else:
            msg = (
                "Coherence gate FAILED (skip_gate_check=True, continuing)."
                if skip_gate_check
                else "Coherence gate FAILED. Results will be written; check model quality."
            )
            logger.warning(
                "%s  n_coherent=%d mean=%.3f",
                msg,
                gate_report["n_coherent_topics"],
                gate_report["mean_coherence"],
            )

        # --- Step 5: Clear stale results (topic IDs aren't stable across runs) ---
        conn.execute("DELETE FROM topics")
        conn.execute("DELETE FROM topic_assignments")
        conn.execute("DELETE FROM topic_over_time")
        conn.commit()

        # --- Step 6: Write topics ---
        topics_rows = [
            (
                info["topic_id"],
                json.dumps(info["keywords"]),
                info["doc_count"],
                coherence_by_id.get(info["topic_id"]),
            )
            for info in topic_info
        ]
        upsert_topics(conn, topics_rows)

        # --- Step 7: Write topic assignments (batched to avoid binding limits) ---
        assignment_rows = [
            (doc_id, int(tid), float(p))
            for doc_id, tid, p in zip(all_ids, topic_assignments, probs)
        ]
        for i in range(0, len(assignment_rows), batch_size):
            upsert_topic_assignments(conn, assignment_rows[i : i + batch_size])

        # --- Step 8: Temporal tracking ---
        # Partition already-assigned docs by ISO week; no retraining needed.
        doc_week_topic = []
        for doc_id, tid, ts_str in zip(all_ids, topic_assignments, all_source_timestamps):
            if int(tid) == OUTLIER_TOPIC_ID or not ts_str:
                continue
            week = _week_start(str(ts_str))
            if week:
                doc_week_topic.append((doc_id, int(tid), week))

        if doc_week_topic:
            sentiment_map: Dict[str, float] = {}
            chunk_ids = [x[0] for x in doc_week_topic]
            for i in range(0, len(chunk_ids), _SENTIMENT_BATCH):
                chunk = chunk_ids[i : i + _SENTIMENT_BATCH]
                placeholders = ",".join("?" * len(chunk))
                rows = conn.execute(
                    f"SELECT id, label FROM sentiment_predictions WHERE id IN ({placeholders})",
                    chunk,
                ).fetchall()
                for row in rows:
                    sentiment_map[row["id"]] = SENTIMENT_SCORE_MAP.get(row["label"], 0.0)

            week_topic_scores: Dict[Tuple[int, str], List[Optional[float]]] = defaultdict(list)
            for doc_id, tid, week in doc_week_topic:
                week_topic_scores[(tid, week)].append(sentiment_map.get(doc_id))

            tot_rows = []
            for (tid, week), scores in week_topic_scores.items():
                valid = [s for s in scores if s is not None]
                avg = sum(valid) / len(valid) if valid else None
                tot_rows.append((tid, week, len(scores), avg))
            upsert_topic_over_time(conn, tot_rows)

        # --- Step 9: MLflow metrics ---
        n_topics = sum(1 for info in topic_info if info["topic_id"] != OUTLIER_TOPIC_ID)
        n_outliers = list(topic_assignments).count(OUTLIER_TOPIC_ID)

        if _mlflow_run is not None:
            try:
                import mlflow

                mlflow.log_metrics(
                    {
                        "total_docs": total_docs,
                        "n_topics": n_topics,
                        "n_outliers": n_outliers,
                        "coherent_topic_count": gate_report["n_coherent_topics"],
                        "mean_coherence": gate_report["mean_coherence"],
                        "gate_passed": int(gate_passed),
                    }
                )
                mlflow.end_run()
            except Exception as exc:
                logger.warning("MLflow metric logging failed: %s", exc)

        return {
            "total_docs": total_docs,
            "n_topics": n_topics,
            "n_outliers": n_outliers,
            "coherent_topic_count": gate_report["n_coherent_topics"],
            "mean_coherence": gate_report["mean_coherence"],
            "gate_passed": gate_passed,
            "device": device,
            "days": days,
        }

    finally:
        conn.close()
